### ISSUE TITLE
Import issue with Server Side Rendering

### ISSUE THREAD

**Issue by TheTruth219** [whawker/react-jsx-highcharts-examples#2]
I'm working on a Gatsby site and trying to figure out the best way to deal with the SSR issues that pop up when Highcharts looks for the window object. I've tried checking for the window before executing, putting the chart in componentDidMount(), etc. , but I've found the issue goes away only when I remove the import for the library. 

I've also tried handling it by trying to lazyload the library, but that's not working either. Any Ideas?

![Screen Shot 2019-08-28 at 11 02 55 AM](https://user-images.githubusercontent.com/36748331/63880875-6beb6b00-c983-11e9-9532-21121bd17633.png)

**Comment by anajavi** [comment]
Can you post this issue to https://github.com/whawker/react-jsx-highcharts repository? This repository is used only for examples.

I am not too familiar with server side rendering, but maybe someone else can help you there.

**Comment by anajavi** [comment]
This is actually fixable in [react-jsx-highcharts](https://github.com/whawker/react-jsx-highcharts).

Please post this issue to that repository, it should be quite easy to fix.

I will close this issue now.
